### ISSUE TITLE
how to get current weapon id?

### ISSUE THREAD

**Issue by whisp1488** [bruhmoment21/cs2-sdk#36]

**Comment by bruhmoment21** [comment]
https://github.com/bruhmoment21/cs2-sdk/blob/2a833a917596316561618f69eeb6d4ba36168ad0/cs2cheat/src/sdk/source2-sdk/entity/c_econitemview.hpp#L17-L18

**Comment by whisp1488** [comment]
> https://github.com/bruhmoment21/cs2-sdk/blob/2a833a917596316561618f69eeb6d4ba36168ad0/cs2cheat/src/sdk/source2-sdk/entity/c_econitemview.hpp#L17-L18

use like:
local_player->weapon_servie()->active_weapon().Get<weapon_t>()->m_iItemDefinitionIndex();
?

**Comment by bruhmoment21** [comment]
you need to access ceconitemview which you is found in attributemanager which is found in https://github.com/bruhmoment21/cs2-sdk/blob/2a833a917596316561618f69eeb6d4ba36168ad0/cs2cheat/src/sdk/source2-sdk/entity/c_econentity.hpp#L8-L9

i will close this issue since you can see examples in skin_changer.cpp
