### ISSUE TITLE
Injection Method / Recommended Injector

### ISSUE THREAD

**Issue by emreires** [bruhmoment21/cs2-sdk#84]
While trying to inject the SDK from memory (DLL binaries in unsigned char) to game, it doesnt work. Using load library.
Any ideas?

**Comment by carrved** [comment]
same here, using extreme injector with manual map since other methods just error
any reccomendations?

**Comment by amrahamirash** [comment]
> While trying to inject the SDK from memory (DLL binaries in unsigned char) to game, it doesnt work. Using load library. Any ideas?

You can check this injector: https://www.youtube.com/watch?v=qY2RANxloCg&pp=ygUJa29ueWFsxLFt

**Comment by neoneeeee** [comment]
Write your own manual map injector and add dll to safe modules on init you can look at bakaware how dumbasPL does it.

**Comment by dumbasPL** [comment]
Since someone mentioned me, I'm just going to shameless plug [fumo_loader](https://github.com/dumbasPL/fumo_loader). On a more serious note, an injector is not enough to keep you safe. For starters, this project uses trampoline hooks, and that's a big no-no since read-only sections are checked for integrity. Make sure to read Limitations and Caveats before trying to use my loader since I'm 110% sure it won't work with this base without heavy modifications to make it manual-mapable.

**Comment by bruhmoment21** [comment]
read readme for manual map support
